"""added email for users

Revision ID: 6b151f1261c6
Revises: 56589fda8ef1
Create Date: 2021-12-14 14:54:00.960163

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6b151f1261c6'
down_revision = '56589fda8ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.alter_column('user', 'username',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=True)
    op.alter_column('user', 'password',
                    existing_type=sa.VARCHAR(length=128),
                    nullable=True)
    op.alter_column('user', 'role',
                    existing_type=sa.VARCHAR(length=30),
                    nullable=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.alter_column('user', 'role',
                    existing_type=sa.VARCHAR(length=30),
                    nullable=False)
    op.alter_column('user', 'password',
                    existing_type=sa.VARCHAR(length=128),
                    nullable=False)
    op.alter_column('user', 'username',
                    existing_type=sa.VARCHAR(length=64),
                    nullable=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
